const host = process.env.REACT_APP_HOST;
const Url = {
  Websocket: host + "/websocket",
  Login: host + "/auth/login",
  RefreshToken: host + "/auth/refresh-token",
  UserData: host + "/user",
  Room: host + "/room",
  UserInfoBySocketId: host + "/user/socketId",
  RoomInfo: host + "/room",
  UserRegister: host + "/auth/signup",
  TrainerRoom: host + "/trainer/room",
  TrainerMeal: host + "/trainer/meal",
  TrainerTraining: host + "/trainer/training",
  TrainerExercise: host + "/trainer/exercise",
  TrainerTrainee: host + "/trainer/trainee",
  TrainerMealProgram: host + "/trainer/meal-program",
  TrainerCurrentTrainee: host + "/trainer/current-trainee",
  TrainerRegisteredTrainee: host + "/trainer/registered-trainee",
  TrainerTraineeData: host + "/trainer/trainee",
  AdminUser: host + "/admin/user",
  AdminTrainer: host + "/admin/trainer",
  AdminUserTrainer: host + "/admin/user-trainer",
  AdminUserTrainerRegister: host + "/admin/user-trainer-register",
  AdminChangeRole: host + "/admin/change-role",
  MealImage: host + "/file/image",
  ExerciseVideo: host + "/file/video",
};
export default Url;