GET https://graduate-server-project.herokuapp.com/meal

###
GET https://graduate-server-project.herokuapp.com/training

###
POST https://graduate-server-project.herokuapp.com/auth/login HTTP/1.1
content-type: application/json

{
    "email": "user2",
    "password": "user2"
}

###
GET https://graduate-server-project.herokuapp.com/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWQiOiI2MDUyMGQ3MmYyY2JjNmFlYmQ1YmM3NGUiLCJpYXQiOjE2MTU5OTI4NDIsImV4cCI6MTYxNTk5NjQ0Mn0.3e_501R-YnEcvynK6L7_QOTMKWAjJLgOn3IhGEB-gd0

###
POST http://localhost:3010/auth/login HTTP/1.1
content-type: application/json

{
    "email": "congnv@gmail.com",
    "password": "congnv"
}

###
GET http://localhost:3010/room/trainer
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbmdudkBnbWFpbC5jb20iLCJpZCI6IjYwODZkMjQ0NDk0MDIxMGYwZTM0MzI3MiIsImlhdCI6MTYxOTQ0ODQxOCwiZXhwIjoxNjE5NDUyMDE4fQ.YVMojbtjaLCwPMjvuzEg6or6Mh_XMe3fbTq2y2WK-R4

{
    "name": "room1"
}

###
GET http://localhost:3010/trainer/meal
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbmdudkBnbWFpbC5jb20iLCJpZCI6IjYwODZkMjQ0NDk0MDIxMGYwZTM0MzI3MiIsImlhdCI6MTYxOTQ0ODQxOCwiZXhwIjoxNjE5NDUyMDE4fQ.YVMojbtjaLCwPMjvuzEg6or6Mh_XMe3fbTq2y2WK-R4

